version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "80:80"
    volumes:
      - ./:/app
#      - /home/lehongduc3491/uploaded_source_code:/data/uploaded
#      - /home/lehongduc3491/extracted_source_code:/data/extracted
#      - /home/lehongduc3491/replaced_compressed_source_code:/data/replaced
      - /home/ubuntu/uploaded_source_code:/data/uploaded
      - /home/ubuntu/extracted_source_code:/data/extracted
      - /home/ubuntu/replaced_compressed_source_code:/data/replaced
    environment:
      - FLASK_ENV=development
      - UPLOAD_DIR=/data/uploaded
      - EXTRACT_DIR=/data/extracted
      - REPLACED_DIR=/data/replaced
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=upload_app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: flask_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: upload_app
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  db_data: