version: '3.8'

services:
  app:
    build: .
    container_name: industry-project-app
    ports:
      - "80:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./extracted:/app/extracted
    restart: always
