version: '3.8'

services:
  web_app_upload:
    build: .
    container_name: vm1_upload_app
    restart: always
    ports:
      - "80:5000"
    volumes:
      - /home/lehongduc3491/uploaded_source_code:/data/uploads
      - /home/lehongduc3491/extracted_source_code:/data/extracted
    environment:
      UPLOAD_FOLDER: /data/uploads
      EXTRACT_FOLDER: /data/extracted
