version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    # app không publish thẳng ra host nữa, chỉ expose cho Nginx
    expose:
      - "80"
    environment:
      - FLASK_ENV=development
      - UPLOAD_DIR=/data/uploaded
      - EXTRACT_DIR=/data/extracted
      - REPLACED_DIR=/data/replaced
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=upload_app
    volumes:
      - ./:/app
      - /home/ubuntu/uploaded_source_code:/data/uploaded
      - /home/ubuntu/extracted_source_code:/data/extracted
      - /home/ubuntu/replaced_compressed_source_code:/data/replaced
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/healthz"]
      interval: 10s
      timeout: 3s
      retries: 12

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - /home/ubuntu/maintenance:/etc/nginx/maintenance

  db:
    image: mysql:8.0
    container_name: flask_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: upload_app
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  db_data:
