- name: Setup VM with Docker & Compose
  hosts: targets
  become: true
  tasks:
    - name: Cập nhật hệ thống
      apt:
        update_cache: yes

    - name: Cài đặt Docker
      apt:
        name: docker.io
        state: present

    - name: Cài đặt Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "0755"

    - name: Tạo symlink docker-compose
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
        force: true

    - name: Cấp quyền sudo không mật khẩu
      lineinfile:
        path: /etc/sudoers
        line: "ubuntu ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: Thêm user vào nhóm docker
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Run hello-world container
      command: docker run hello-world
      register: result
      ignore_errors: true

    - name: Hiển thị kết quả hello-world
      debug:
        var: result.stdout_lines
